{{- if .Values.devAFDeployment }}
kind: Secret
apiVersion: v1
metadata:
  name: cms-jovyan-secrets
  namespace: {{.Release.Namespace}}
type: Opaque
data:
  ca.pem: {{ .Values.testpem | b64enc | quote }}
  hostcert.pem: {{ .Values.testpem | b64enc | quote }}
  usercert.pem: {{ .Values.testpem | b64enc | quote }}
  xcache_token: {{ .Values.testtoken | b64enc | quote }}
  .servicex: {{ .Values.testtoken | b64enc | quote }}
  ca.key: {{ .Values.testpem | b64enc | quote }}
{{- end }}